name = "BoardGamesStrategies"
uuid = "32f2dd74-f74d-434c-9211-e2f9435e7f91"
authors = ["António Capela"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
